# Generated by Django 3.0.12 on 2021-02-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('function_used', models.CharField(choices=[('CURRENCY_EXCHANGE_RATE', 'Currency exchange rate'), ('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='INTRADAY', max_length=40)),
                ('from_currency', models.CharField(max_length=255)),
                ('to_currency', models.CharField(max_length=255)),
                ('exchange_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('refreshed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
                'ordering': ['-modified'],
            },
        ),
    ]
